#!/bin/sh

echo "Checking code formatting and linting..."

sbt "scalafmtCheckAll; scalafixAll --check"
if [ $? -ne 0 ]; then
  echo ""
  echo "[FAIL] Formatting or linting checks failed."
  echo "Run 'sbt scalafmtAll scalafixAll' in your terminal to fix them automatically."
  exit 1
fi

echo "[SUCCESS] Code looks clean. Proceeding with commit."
exit 0
