rules = [
  RemoveUnused,
  OrganizeImports,
  DisableSyntax,
  ExplicitResultTypes,
]

ExplicitResultTypes {
  memberKind = [Def, Val, Var]
  memberVisibility = [Public, Protected]
}

OrganizeImports {
  blankLines = Auto
  coalesceToWildcardImportThreshold = 3
  groupedImports = Merge
  groups = ["*", "scala.", "java."]
  removeUnused = true
}

DisableSyntax {
  noNulls = true
  noThrows = true
  noReturns = true
  noAsInstanceOf = true
  noIsInstanceOf = true
}
